[workspace]
members = [ "chokotto_client", "chokotto_server" ]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
