[package]
name = "chokotto_home_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
local-ip-address = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
salvo = { version = "0.74.1", features = ["anyhow"] }
anyhow = "1.0.93"
dirs = "5.0.1"
